name: Deploy Players job

on:
  push:
    branches: [ "main" ]
    paths:
      - "players_job/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      # Docker login to Artifact Registry
      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet

      # Build image
      - name: Build Docker image
        run: |
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/containers/players-job:latest ./players_job

      # Push image
      - name: Push Docker image
        run: |
          docker push europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/containers/players-job:latest

      # Deploy to Cloud Run JOB
      - name: Deploy to Cloud Run
        run: |
          gcloud run jobs deploy players-job \
            --image europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/containers/players-job:latest \
            --region europe-west9 \
            --quiet